INSERT INTO damages(category, name) VALUES
  ('insects', 'Douglas-fir beetle'),
  ('insects', 'Mt pine Beetle'),
  ('insects', 'Western pine beetle'),
  ('insects', 'Pine engraver (Ips) beetle'),
  ('insects', 'Turpentine beetle'),
  ('insects', 'Spruce beetle'),
  ('insects', 'Fir engraver beetle'),
  ('insects', 'Flat-headed wood borer'),
  ('insects', 'Long-horned wood borer'),
  ('insects', 'Emerald ash borer (invasive)'),
  ('insects', 'Mediterranean oak borer (invasive)'),
  ('insects', 'Asian longhorned beetle (invasive)'),
  ('insects', 'Western spruce budworm'),
  ('insects', 'Tussock moth'),
  ('insects', 'Pandora moth'),
  ('insects', 'Pine butterfly'),
  ('insects', 'Larch casebearer'),
  ('insects', 'Oak Looper'),
  ('insects', 'Spruce aphid'),
  ('insects', 'Balsam woolly adelgid'),
  ('insects', 'Pine needle SCALE'),
  ('insects', 'Elongated hemlock scale (invasive)'),
  ('insects', 'Western pine shoot borer'),
  ('insects', 'Sequoia pitch moth'),
  ('insects', 'Oystershell scale'),
  ('diseases', 'Laminated root rot'),
  ('diseases', 'Armillaria root rot'),
  ('diseases', 'Annosus root rot'),
  ('diseases', 'Black stain'),
  ('diseases', 'Port-Orford-cedar root disease'),
  ('diseases', 'Schweinitzii root & butt rot'),
  ('diseases', 'Phellinus pini'),
  ('diseases', 'Indian paint fungus'),
  ('diseases', 'Swiss needle CAST'),
  ('diseases', 'Dothistroma needle blight (of pines)'),
  ('diseases', 'Elytroderma disease (of ponderosa pine)'),
  ('diseases', 'Diplodia'),
  ('diseases', 'Western gall rust'),
  ('diseases', 'White pine blister rust'),
  ('diseases', 'Commandra rust'),
  ('invasives', 'False-brome'),
  ('invasives', 'Cheatgrass'),
  ('invasives', 'Scotch broom'),
  ('invasives', 'Gorse'),
  ('invasives', 'Holly'),
  ('invasives', 'Blackberries'),
  ('invasives', 'Honey suckle'),
  ('invasives', 'Ivy'),
  ('invasives', 'Knapweed'),
  ('invasives', 'Shiny-leaf gerannium');
